# pull app từ hub docker
FROM nginx

WORKDIR /usr/share/nginx/html

# copy tất cả source ngang cấp với Dockerfile vào thư mục chi định ở container
COPY . .

EXPOSE 80
# docker build . -t img-html

# do