name: demo 
on: 
    push:
        branches: [main]
jobs:
    job_A:
        runs-on: ubuntu-latest 
        steps:
            - run: echo 'hello world again' 
    job_B:
        runs-on: ubuntu-latest 
        steps:
            - run: df -h
    job_C:
        runs-on: ubuntu-latest 
        steps:
            - run: free -h